goal = [0.77, -0.13, 0.0]

grid_size = 3

[wooden_boxes]

[wooden_boxes.wooden_box_1]
name = "WB1"
position = [-0.75, -0.13, 0.2]
DEF = "WB"

[wooden_boxes.wooden_box_2]
name = "WB2"
position = [-0.82, 1.0, 0.2]
DEF = "WB"
