
grid_size = 9.0

grid = [3.0, 3.0]

[wooden_boxes]
WB1.name = 'WB1'
WB1.position = [0.3, 0.2]
WB1.DEF = 'WB1'

[robot]
PIONEER2.name = 'PIONEER2'
PIONEER2.position = [-0.13, 0.0]
PIONEER2.DEF = 'PIONEER2'

goal = [-0.5, 0.0]
