
goal = [[0.98, -1.09, 0.0]]

grid_size = 3.0

[wooden_boxes]
WB1.name = 'WB1'
WB1.position = [-0.75, 0.3, 0.2]
WB2.name = 'WB2'
WB2.position = [0.7, -0.3, 0.2]
WB3.name = 'WB3'
WB3.position = [-0.6, -0.95, 0.2]

[robot]
PIONEER2.name = 'PIONEER2'
PIONEER2.position = [-0.06, -0.13, 0.0]
