
goal = [[0.669498, 0.0309992, -4.03233e-13]]

grid_size = 3.0

[wooden_boxes]
WB1.name = 'WB1'
WB1.position = [0.03, -0.825, 0.2]
WB2.name = 'WB2'
WB2.position = [-0.42, -0.825, 0.2]
WB3.name = 'WB3'
WB3.position = [-1.0, -0.825, 0.2]
WB4.name = 'WB4'
WB4.position = [-1.0, 0.825, 0.2]
WB5.name = 'WB5'
WB5.position = [0.03, 0.825, 0.2]
WB6.name = 'WB6'
WB6.position = [-0.425, 0.825, 0.2]

[robot]
PIONEER2.name = 'PIONEER2'
PIONEER2.position = [-0.98, 0.0, 0.0]
