[wooden_box_1]
name = "WB1"
position = [0.5, 0.0, 0.2]
DEF = "WB"

[wooden_box_2]
name = "WB2"
position = [0.0, 0.5, 0.2]
DEF = "WB"

[wooden_box_3]
name = "WB3"
position = [0.0, -0.5, 0.2]
DEF = "WB"
