
goal = [0.77, -0.13, 0.0]

grid_size = 9.0

grid = [3.0, 3.0]

[wooden_boxes]
WB1.name = 'WB1'
WB1.position = [-0.02, -0.19, 0.2]
WB2.name = 'WB2'
WB2.position = [0.96, 1.01, 0.2]
WB3.name = 'WB3'
WB3.position = [-0.02, -0.95, 0.2]
WB4.name = 'WB4'
WB4.position = [-0.97, -0.95, 0.2]

[robot]
PIONEER2.name = 'PIONEER2'
PIONEER2.position = [-0.98, -0.13, 0.0]
