goal = [0.77, -0.13, 0.0]
grid_size = 3.0

[wooden_boxes]
wooden_box_1.name = 'WB1'
wooden_box_1.position = [-0.02, -0.07, 0.2]
wooden_box_1.DEF = 'WB'

wooden_box_2.name = 'WB2'
wooden_box_2.position = [0.96, 1.01, 0.2]
wooden_box_2.DEF = 'WB'

wooden_box_3.name = 'WB3'
wooden_box_3.position = [-0.02, 0.95, 0.2]
wooden_box_3.DEF = 'WB'

wooden_box_4.name = 'WB4'
wooden_box_4.position = [-0.97, -0.95, 0.2]
wooden_box_4.DEF = 'WB'
