
grid_size = 9.0

grid = [3.0, 3.0]

[wooden_boxes]
WB1.name = 'WB1'
WB1.position = [0.77, -0.13, 0.2]

[robot]
PIONEER2.name = 'PIONEER2'
PIONEER2.position = [0.0, -0.13, 0.0]

goal = [-0.75, -0.13, 0.0]
